name: Compile and Run vm.h examples
on: [push, pull_request]

jobs:
  windows:
    strategy:
      matrix:
        cc: [gcc]
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: choco install -y llvm mingw
      - name: Compile vm examples
        run: ${{ matrix.cc }} -s -O2 -mconsole -march=native -mtune=native -std=c89 -pedantic -nodefaultlibs -nostdlib -mno-stack-arg-probe -Xlinker /STACK:0x100000,0x100000 -fno-builtin -ffreestanding -fno-asynchronous-unwind-tables -fuse-ld=lld -fsanitize=undefined -Wall -Wextra -Werror -Wvla -Wconversion -Wdouble-promotion -Wmissing-field-initializers -Wno-uninitialized -Winit-self -Wunused -Wunused-macros -Wunused-local-typedefs examples/vm_win32_nostdlib.c -o vm_win32_nostdlib_${{ matrix.cc }}.exe -lkernel32
      - name: Run vm examples
        run: .\vm_win32_nostdlib_${{ matrix.cc }}.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-latest-${{ matrix.cc }}-vm_win32_nostdlib
          path: vm_win32_nostdlib_${{ matrix.cc }}.exe
